[package]
name = "artzified/parallelizer"
version = "1.0.4"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
license = "MIT"
exclude = ["node_modules", "docs", ".github", "*.rbxl", "*.rbxmx", "*.rbxml", "*.rbxm", "dev.project.json"]
repository = "https://github.com/Artzified/parallelizer"

[dependencies]